def show_menu():
    print("\n--- Calculadora de Hábitos Saludables ---")
    print("1. Registrar nuevo hábito")
    print("2. Registrar entrada diaria")
    print("3. Ver historial")
    print("4. Salir")
    print("5. Exportar historial a CSV y crear backup")
    print("6. Ver resumen semanal")
    print("7. Ver gráfico semanal (ASCII)")
    return input("Seleccione una opción: ")
